# Generated by Django 2.2.3 on 2020-01-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=False)),
                ('concluded', models.BooleanField(default=False)),
                ('loading', models.BooleanField(default=False)),
                ('transportation', models.BooleanField(default=False)),
                ('unloading', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статус сделки',
                'verbose_name_plural': 'Статусы сделок',
            },
        ),
        migrations.CreateModel(
            name='LocationCoordinatesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус координата',
                'verbose_name_plural': 'Статусы координат',
            },
        ),
        migrations.CreateModel(
            name='ParametresTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heightNoLess', models.IntegerField(default=1)),
                ('lackOfSmell', models.BooleanField(default=False)),
                ('lackOfThings', models.BooleanField(default=False)),
                ('woodenFloor', models.BooleanField(default=False)),
                ('dopple', models.BooleanField(default=False)),
                ('demin', models.IntegerField(default=1)),
                ('connik', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Параметр прицепа',
                'verbose_name_plural': 'Параметры прицепа',
            },
        ),
        migrations.CreateModel(
            name='SubclassHazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Опасность',
                'verbose_name_plural': 'Опасности',
            },
        ),
        migrations.CreateModel(
            name='TypeAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип авто',
                'verbose_name_plural': 'Типы автомобиля',
            },
        ),
        migrations.CreateModel(
            name='TypeCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='TypeLoading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип погрузки',
                'verbose_name_plural': 'Типы погрузки',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ед.изм.',
                'verbose_name_plural': 'Ед.изм.',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.IntegerField(default=1)),
                ('maximum', models.IntegerField(default=10)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Units')),
            ],
            options={
                'verbose_name': 'Вес',
                'verbose_name_plural': 'Вес',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('length', models.IntegerField(default=1)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Units')),
            ],
            options={
                'verbose_name': 'Объём',
                'verbose_name_plural': 'Объёмы',
            },
        ),
        migrations.CreateModel(
            name='LocationCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationCoordinates', models.CharField(max_length=255)),
                ('sendingTimeCoordinates', models.TextField()),
                ('locationCoordinatesStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.LocationCoordinatesStatus')),
            ],
            options={
                'verbose_name': 'Местоположения груза',
                'verbose_name_plural': 'Местоположения грузов',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberDealFromClient', models.CharField(max_length=50)),
                ('priceClient', models.IntegerField(default=0)),
                ('companyProfit', models.IntegerField(default=0)),
                ('fromDeal', models.CharField(max_length=255)),
                ('toDeal', models.CharField(max_length=255)),
                ('dateLoading', models.DateTimeField()),
                ('dateUnloading', models.DateTimeField()),
                ('autoReleaseYear', models.IntegerField()),
                ('countPallet', models.IntegerField()),
                ('stateAwning', models.CharField(max_length=100)),
                ('requirementsLoading', models.CharField(max_length=100)),
                ('dealStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.DealStatus')),
                ('locationCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.LocationCargo')),
                ('parametresTrailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.ParametresTrailer')),
                ('subclassHazard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.SubclassHazard')),
                ('typeAuto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.TypeAuto')),
                ('typeCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.TypeCargo')),
                ('typeLoading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.TypeLoading')),
                ('volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Volume')),
                ('weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Weight')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
