# Generated by Django 3.0.2 on 2020-02-21 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deal', '0003_deal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='dateLoading',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='dateUnloading',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='dealStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealStatuses', to='Deal.DealStatus'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='locationCargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationCargos', to='Deal.LocationCargo'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='parametresTrailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametresTrailers', to='Deal.ParametresTrailer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='subclassHazard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclassHazards', to='Deal.SubclassHazard'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='typeAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typesAuto', to='Deal.TypeAuto'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='typeCargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typesCargo', to='Deal.TypeCargo'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='typeLoading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typesLoading', to='Deal.TypeLoading'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='Deal.Volume'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weights', to='Deal.Weight'),
        ),
    ]
