# Generated by Django 3.0.2 on 2020-02-29 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationCoordinates', models.CharField(max_length=255, verbose_name='Координаты местоположения')),
                ('sendingTimeCoordinates', models.TextField(verbose_name='Время отправки координат')),
            ],
            options={
                'verbose_name': 'Местоположение груза',
                'verbose_name_plural': 'Местоположения грузов',
            },
        ),
        migrations.CreateModel(
            name='LocationCoordinatesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус координата',
                'verbose_name_plural': 'Статусы координат',
            },
        ),
        migrations.CreateModel(
            name='ParametresTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heightNoLess', models.IntegerField(default=1, verbose_name='Высота не меньше')),
                ('lackOfSmell', models.BooleanField(default=False, verbose_name='Отсутствие запахов')),
                ('lackOfThings', models.BooleanField(default=False, verbose_name='Отсутствие выступающих вещей')),
                ('woodenFloor', models.BooleanField(default=False, verbose_name='Деревянный пол')),
                ('dopple', models.BooleanField(default=False, verbose_name='Наличие допельштоков')),
                ('demin', models.IntegerField(default=1, verbose_name='Кол-во ремней')),
                ('connik', models.IntegerField(default=1, verbose_name='Кол-во конников')),
            ],
            options={
                'verbose_name': 'Параметр прицепа',
                'verbose_name_plural': 'Параметры прицепа',
            },
        ),
        migrations.CreateModel(
            name='TypeAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип авто',
                'verbose_name_plural': 'Типы автомобиля',
            },
        ),
        migrations.CreateModel(
            name='TypeCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='TypeLoading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип погрузки',
                'verbose_name_plural': 'Типы погрузки',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ед.изм.',
                'verbose_name_plural': 'Ед.изм.',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=1, verbose_name='Ширина')),
                ('height', models.IntegerField(default=1, verbose_name='Высота')),
                ('length', models.IntegerField(default=1, verbose_name='Длина')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Units', verbose_name='Ед.измерения')),
            ],
            options={
                'verbose_name': 'Объём',
                'verbose_name_plural': 'Объёмы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOrderFromClient', models.CharField(max_length=50, verbose_name='Номер заказа клиента')),
                ('priceClient', models.IntegerField(default=0, verbose_name='Цена клиента')),
                ('companyProfit', models.IntegerField(default=0, verbose_name='Прибыль компании')),
                ('fromOrder', models.CharField(blank=True, max_length=255, verbose_name='Дата начала заказа')),
                ('toOrder', models.CharField(blank=True, max_length=255, verbose_name='Дата завершения заказа')),
                ('dateLoading', models.DateField(blank=True, verbose_name='Дата погрузки')),
                ('dateUnloading', models.DateField(blank=True, verbose_name='Дата выгрузки')),
                ('autoReleaseYear', models.IntegerField(verbose_name='Год выпуска авто')),
                ('countPallet', models.IntegerField(verbose_name='Количество паллет')),
                ('stateAwning', models.CharField(max_length=100, verbose_name='Состояние тента')),
                ('requirementsLoading', models.CharField(max_length=100, verbose_name='Требования погрузки')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('orderStatus', models.SmallIntegerField(blank=True, choices=[(0, 'Новая'), (1, 'Заключена'), (2, 'Погрузка'), (3, 'Транспортировка'), (4, 'Выгрузка'), (5, 'Завершена'), (6, 'Отменена')], default=None, verbose_name='Статус заказа')),
                ('locationCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationCargo', to='Deal.LocationCargo', verbose_name='Местоположение груза')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('parametresTrailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametresTrailer', to='Deal.ParametresTrailer', verbose_name='Параметры заказа')),
                ('typeAuto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeAuto', to='Deal.TypeAuto', verbose_name='Тип авто')),
                ('typeCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeCargo', to='Deal.TypeCargo', verbose_name='Тип груза')),
                ('typeLoading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeLoading', to='Deal.TypeLoading', verbose_name='Тип погрузки')),
                ('volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume', to='Deal.Volume', verbose_name='Объём')),
                ('weightMeasurementUnit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weightMeasurementUnit', to='Deal.Units', verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.AddField(
            model_name='locationcargo',
            name='locationCoordinatesStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.LocationCoordinatesStatus', verbose_name='Статус координат местоположения'),
        ),
    ]
