# Generated by Django 2.2.3 on 2020-04-09 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('sendingTimeCoordinates', models.CharField(blank=True, default=datetime.time(15, 7, 5, 137329), max_length=255, verbose_name='Время отправки координат')),
            ],
            options={
                'verbose_name': 'Местоположение груза',
                'verbose_name_plural': 'Местоположения грузов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Название')),
                ('priceClient', models.IntegerField(default=0, verbose_name='Цена клиента')),
                ('companyProfit', models.IntegerField(default=0, verbose_name='Прибыль компании')),
                ('fromOrder', models.DateField(blank=True, null=True, verbose_name='Дата начала заказа')),
                ('toOrder', models.DateField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('dateLoading', models.DateField(blank=True, null=True, verbose_name='Дата погрузки')),
                ('dateUnloading', models.DateField(blank=True, null=True, verbose_name='Дата выгрузки')),
                ('autoReleaseYear', models.IntegerField(default=0, verbose_name='Год выпуска авто')),
                ('requirementsLoading', models.CharField(blank=True, default='', max_length=100, verbose_name='Требования погрузки')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('orderStatus', models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'Заключена'), ('2', 'Погрузка'), ('3', 'Транспортировка'), ('4', 'Выгрузка'), ('5', 'Завершена'), ('6', 'Отменена')], default='Новая', max_length=10, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
        migrations.CreateModel(
            name='ParametresTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heightNoLess', models.IntegerField(default=1, verbose_name='Высота не меньше')),
                ('lackOfSmell', models.BooleanField(default=False, verbose_name='Отсутствие запахов')),
                ('lackOfThings', models.BooleanField(default=False, verbose_name='Отсутствие выступающих вещей')),
                ('woodenFloor', models.BooleanField(default=False, verbose_name='Деревянный пол')),
                ('dopple', models.BooleanField(default=False, verbose_name='Наличие допельштоков')),
                ('demin', models.IntegerField(default=1, verbose_name='Кол-во ремней')),
                ('connik', models.IntegerField(default=1, verbose_name='Кол-во конников')),
            ],
            options={
                'verbose_name': 'Параметр прицепа',
                'verbose_name_plural': 'Параметры прицепа',
            },
        ),
        migrations.CreateModel(
            name='StateAwning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noHoles', models.BooleanField(default=False, verbose_name='Без дыр')),
                ('noGaps', models.BooleanField(default=False, verbose_name='Без щелей')),
                ('dry', models.BooleanField(default=False, verbose_name='Сухой')),
                ('noPatches', models.BooleanField(default=False, verbose_name='Отсутствие заплаток')),
            ],
            options={
                'verbose_name': 'Состояние тента',
                'verbose_name_plural': 'Состояния тентов',
            },
        ),
        migrations.CreateModel(
            name='TypeAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип авто',
                'verbose_name_plural': 'Типы автомобиля',
            },
        ),
        migrations.CreateModel(
            name='TypeCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='TypeLoading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип погрузки',
                'verbose_name_plural': 'Типы погрузки',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ед.изм.',
                'verbose_name_plural': 'Ед.изм.',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0.0, verbose_name='Ширина')),
                ('height', models.FloatField(default=0.0, verbose_name='Высота')),
                ('length', models.FloatField(default=0.0, verbose_name='Длина')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Units', verbose_name='Ед.изм. объёма')),
            ],
            options={
                'verbose_name': 'Объём',
                'verbose_name_plural': 'Объёмы',
            },
        ),
    ]
