# Generated by Django 3.0.2 on 2020-02-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcargo',
            options={'verbose_name': 'Местоположение груза', 'verbose_name_plural': 'Местоположения грузов'},
        ),
    ]
