# Generated by Django 2.2.3 on 2020-04-09 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Deal', '0001_initial'),
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='app.Driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='locationCargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationCargo', to='Deal.LocationCargo', verbose_name='Местоположение груза'),
        ),
        migrations.AddField(
            model_name='order',
            name='stateAwning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateAwning', to='Deal.StateAwning', verbose_name='Состояние тента'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeAuto', to='Deal.TypeAuto', verbose_name='Тип авто'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeCargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeCargo', to='Deal.TypeCargo', verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeLoading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeLoading', to='Deal.TypeLoading', verbose_name='Тип погрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume', to='Deal.Volume', verbose_name='Объём'),
        ),
        migrations.AddField(
            model_name='order',
            name='weightMeasurementUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weightMeasurementUnit', to='Deal.Units', verbose_name='Ед. изм. веса'),
        ),
    ]
