# Generated by Django 3.0.2 on 2020-03-18 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Deal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='parametresTrailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametresTrailer', to='Deal.ParametresTrailer', verbose_name='Параметры заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeAuto', to='Deal.TypeAuto', verbose_name='Тип авто'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeCargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeCargo', to='Deal.TypeCargo', verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeLoading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeLoading', to='Deal.TypeLoading', verbose_name='Тип погрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume', to='Deal.Volume', verbose_name='Объём'),
        ),
        migrations.AddField(
            model_name='order',
            name='weightMeasurementUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weightMeasurementUnit', to='Deal.Units', verbose_name='Ед. изм.'),
        ),
        migrations.AddField(
            model_name='locationcargo',
            name='locationCoordinatesStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.LocationCoordinatesStatus', verbose_name='Статус координат местоположения'),
        ),
    ]
