# Generated by Django 2.2.3 on 2020-05-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateOrderConclusion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Дата заключения заказа'),
        ),
    ]
