# Generated by Django 2.2.3 on 2020-04-09 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0002_auto_20200409_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(21, 28, 41, 382505), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
