# Generated by Django 2.2.3 on 2020-05-07 19:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0002_order_dateorderconclusion'),
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='app.Driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='locationCargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationCargo', to='Deal.LocationCargo', verbose_name='Местоположение груза'),
        ),
        migrations.AddField(
            model_name='order',
            name='numberOrderFromClient',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер заказа клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='stateAwning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateAwning', to='Deal.StateAwning', verbose_name='Состояние тента'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeAuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeAuto', to='Deal.TypeAuto', verbose_name='Тип авто'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeCargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeCargo', to='Deal.TypeCargo', verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='order',
            name='typeLoading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeLoading', to='Deal.TypeLoading', verbose_name='Тип погрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume', to='Deal.Volume', verbose_name='Объём'),
        ),
        migrations.AddField(
            model_name='order',
            name='weightMeasurementUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weightMeasurementUnit', to='Deal.Units', verbose_name='Ед. изм. веса'),
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(1, 36, 8, 92826), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateLoading',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Дата погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateUnloading',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Дата выгрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fromOrder',
            field=models.CharField(blank=True, default=datetime.date.today, max_length=100, verbose_name='Дата начала заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Заключена', 'Заключена'), ('Погрузка', 'Погрузка'), ('Транспортировка', 'Транспортировка'), ('Выгрузка', 'Выгрузка'), ('Завершена', 'Завершена'), ('Отменена', 'Отменена')], default='Новая', max_length=10, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirementsLoading',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Требования к погрузке'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toOrder',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Дата завершения заказа'),
        ),
        migrations.AlterField(
            model_name='typeauto',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип авто'),
        ),
        migrations.AlterField(
            model_name='typecargo',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип груза'),
        ),
        migrations.AlterField(
            model_name='typeloading',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип погрузки'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Units', verbose_name='Ед.изм.'),
        ),
    ]
