# Generated by Django 3.0.2 on 2020-03-23 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0002_auto_20200318_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcargo',
            name='locationCoordinatesStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numberOrderFromClient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='parametresTrailer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='typeLoading',
        ),
        migrations.AlterField(
            model_name='order',
            name='countPallet',
            field=models.IntegerField(default=0, verbose_name='Количество паллет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateLoading',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateUnloading',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата выгрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Новая'), (1, 'Заключена'), (2, 'Погрузка'), (3, 'Транспортировка'), (4, 'Выгрузка'), (5, 'Завершена'), (6, 'Отменена')], default=0, verbose_name='Статус заказа'),
        ),
    ]
