# Generated by Django 2.2.3 on 2020-04-09 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0003_auto_20200409_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(21, 54, 55, 85286), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Заключена', 'Заключена'), ('Погрузка', 'Погрузка'), ('Транспортировка', 'Транспортировка'), ('Выгрузка', 'Выгрузка'), ('Завершена', 'Завершена'), ('Отменена', 'Отменена')], default='Новая', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
