# Generated by Django 2.2.3 on 2020-05-07 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0003_auto_20200508_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(2, 9, 24, 677250), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='app.Driver', verbose_name='Водитель'),
        ),
    ]
