# Generated by Django 3.0.2 on 2020-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0003_auto_20200323_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='countPallet',
        ),
        migrations.AlterField(
            model_name='order',
            name='fromOrder',
            field=models.DateField(blank=True, default='2020-01-01', verbose_name='Дата начала заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toOrder',
            field=models.DateField(blank=True, default='2020-01-01', verbose_name='Дата завершения заказа'),
        ),
    ]
