# Generated by Django 2.2.3 on 2020-05-07 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0004_auto_20200508_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(2, 9, 30, 413805), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
