# Generated by Django 2.2.3 on 2020-04-09 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0004_auto_20200409_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(23, 43, 47, 776316), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
