# Generated by Django 3.0.2 on 2020-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0004_auto_20200323_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcargo',
            name='locationCoordinates',
        ),
        migrations.AddField(
            model_name='locationcargo',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='locationcargo',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateLoading',
            field=models.DateField(blank=True, default='2020-01-01', verbose_name='Дата погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateUnloading',
            field=models.DateField(blank=True, default='2020-01-01', verbose_name='Дата выгрузки'),
        ),
    ]
