# Generated by Django 2.2.3 on 2020-04-12 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0005_auto_20200409_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('view_own_order', 'Can view own orders'),), 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(20, 36, 39, 565325), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
