# Generated by Django 3.0.2 on 2020-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0005_auto_20200323_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='autoReleaseYear',
            field=models.IntegerField(default=0, verbose_name='Год выпуска авто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirementsLoading',
            field=models.CharField(default='', max_length=100, verbose_name='Требования погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stateAwning',
            field=models.CharField(default='', max_length=100, verbose_name='Состояние тента'),
        ),
    ]
