# Generated by Django 3.0.2 on 2020-03-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0006_auto_20200324_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numberOrderFromClient',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер заказа клиента'),
        ),
    ]
