# Generated by Django 2.2.3 on 2020-04-15 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0006_auto_20200412_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(18, 0, 11, 232701), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Units', verbose_name='Ед.изм.'),
        ),
    ]
