# Generated by Django 2.2.3 on 2020-04-23 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0007_auto_20200415_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numberOrderFromClient',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер заказа клиента'),
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(15, 45, 47, 49244), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fromOrder',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата начала заказа'),
        ),
        migrations.AlterField(
            model_name='typeauto',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип авто'),
        ),
        migrations.AlterField(
            model_name='typecargo',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип груза'),
        ),
        migrations.AlterField(
            model_name='typeloading',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип погрузки'),
        ),
    ]
