# Generated by Django 3.0.2 on 2020-03-24 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deal', '0007_order_numberorderfromclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='numberOrderFromClient',
            field=models.IntegerField(default=0, editable=False, verbose_name='Номер заказа клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weightMeasurementUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weightMeasurementUnit', to='Deal.Units', verbose_name='Ед. изм. веса'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='height',
            field=models.FloatField(default=0.0, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='length',
            field=models.FloatField(default=0.0, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deal.Units', verbose_name='Ед.изм. объёма'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='width',
            field=models.FloatField(default=0.0, verbose_name='Ширина'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('numberOrderFromClient', 'owner')},
        ),
    ]
