# Generated by Django 2.2.3 on 2020-04-23 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0008_auto_20200423_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateOrderConclusion',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения заказа'),
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(22, 12, 52, 919873), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
