# Generated by Django 3.0.2 on 2020-03-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0008_auto_20200324_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
