# Generated by Django 3.0.2 on 2020-03-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0009_auto_20200324_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='numberOrderFromClient',
        ),
        migrations.AddField(
            model_name='order',
            name='typeLoading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeLoading', to='Deal.TypeLoading', verbose_name='Тип погрузки'),
        ),
    ]
