# Generated by Django 2.2.3 on 2020-04-26 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0009_auto_20200423_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(13, 55, 28, 447478), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
