# Generated by Django 3.0.2 on 2020-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0010_auto_20200326_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requirementsLoading',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Требования погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stateAwning',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Состояние тента'),
        ),
    ]
