# Generated by Django 2.2.3 on 2020-05-06 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0010_auto_20200426_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcargo',
            name='address',
        ),
        migrations.AddField(
            model_name='locationcargo',
            name='addressFrom',
            field=models.CharField(default='', max_length=255, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='locationcargo',
            name='addressTo',
            field=models.CharField(default='', max_length=255, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(23, 3, 57, 548252), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
