# Generated by Django 3.0.2 on 2020-03-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0011_auto_20200326_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationCoordinatesStatus',
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки координат'),
        ),
    ]
