# Generated by Django 2.2.3 on 2020-05-07 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0012_auto_20200507_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(17, 46, 51, 525039), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
