# Generated by Django 3.0.2 on 2020-03-26 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deal', '0012_auto_20200326_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='app.Driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(17, 49, 8, 476466), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fromOrder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Дата начала заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[(0, 'Новая'), (1, 'Заключена'), (2, 'Погрузка'), (3, 'Транспортировка'), (4, 'Выгрузка'), (5, 'Завершена'), (6, 'Отменена')], default='Новая', max_length=10, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toOrder',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Дата завершения заказа'),
        ),
    ]
