# Generated by Django 3.0.2 on 2020-03-26 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0013_auto_20200326_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(19, 24, 2, 695785), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
