# Generated by Django 3.0.2 on 2020-03-27 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0014_auto_20200326_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcargo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='locationcargo',
            name='longitude',
        ),
        migrations.AddField(
            model_name='locationcargo',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(20, 49, 10, 965331), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
