# Generated by Django 3.0.2 on 2020-04-05 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0016_auto_20200405_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(23, 35, 43, 479661), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
