# Generated by Django 3.0.2 on 2020-04-06 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0017_auto_20200405_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(22, 18, 35, 683198), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('0', 'Новая'), ('1', 'Заключена'), ('2', 'Погрузка'), ('3', 'Транспортировка'), ('4', 'Выгрузка'), ('5', 'Завершена'), ('6', 'Отменена')], default='Новая', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
