# Generated by Django 3.0.2 on 2020-04-07 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0018_auto_20200406_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(14, 21, 56, 315391), max_length=255, verbose_name='Время отправки координат'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateLoading',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateUnloading',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fromOrder',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toOrder',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения заказа'),
        ),
    ]
