# Generated by Django 3.0.2 on 2020-04-07 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0020_auto_20200407_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(14, 38, 8, 90329), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
