# Generated by Django 2.2.3 on 2020-04-07 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0022_auto_20200407_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(15, 58, 28, 163954), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
