# Generated by Django 2.2.3 on 2020-04-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0023_auto_20200407_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcargo',
            name='sendingTimeCoordinates',
            field=models.CharField(blank=True, default=datetime.time(16, 11, 20, 477572), max_length=255, verbose_name='Время отправки координат'),
        ),
    ]
