# Generated by Django 3.0.2 on 2020-02-19 15:12

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default=1, max_length=6)),
                ('dateOfBirth', models.DateField(default=None, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TradingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('ownerFullName', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'TradingSets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'UserStatuses',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('autoTechPassPhoto', models.ImageField(null=True, upload_to='static')),
                ('trailerTechPassPhoto', models.ImageField(null=True, upload_to='static')),
                ('autoOwnerPass', models.ImageField(null=True, upload_to='static')),
                ('driverPass', models.ImageField(null=True, upload_to='static')),
                ('driverLicense', models.ImageField(null=True, upload_to='static')),
                ('internationalTransportationLicense', models.ImageField(null=True, upload_to='static')),
                ('insurancePolicy', models.ImageField(null=True, upload_to='static')),
            ],
            options={
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Individuals',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(max_length=255, null=True)),
                ('legalAddress', models.CharField(max_length=255)),
                ('IIN', models.CharField(max_length=255)),
                ('bankAccount', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'LegalEntities',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('tradingSet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TradingSet', to_field='name')),
            ],
            options={
                'verbose_name_plural': 'Managers',
                'ordering': ['tradingSet'],
            },
        ),
    ]
