# Generated by Django 2.2.3 on 2020-05-07 19:36

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Deal', '0002_order_dateorderconclusion'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_client', models.BooleanField(default=False, verbose_name='Клиент')),
                ('is_driver', models.BooleanField(default=False, verbose_name='Исполнитель')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Статус')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TradingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('ownerFullName', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО владельца')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('legalAddress', models.CharField(blank=True, max_length=255, verbose_name='Юр. адрес')),
                ('IIN', models.CharField(blank=True, max_length=255, verbose_name='ИИН')),
                ('bankAccount', models.CharField(blank=True, max_length=255, verbose_name='Номер счёта')),
            ],
            options={
                'verbose_name': 'Торговый сет',
                'verbose_name_plural': 'Торговые сеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус пользователя',
                'verbose_name_plural': 'Статусы пользователя',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default=1, max_length=6, verbose_name='Пол')),
                ('dateOfBirth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(default='', max_length=255, null=True, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес проживания')),
                ('autoTechPassPhoto', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Технический паспорт авто')),
                ('trailerTechPassPhoto', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Технический паспорт прицепа')),
                ('autoOwnerPass', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Паспорт владельца')),
                ('driverPass', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Паспорт водителя')),
                ('driverLicense', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Водительская лицензия')),
                ('internationalTransportationLicense', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Лицензия на международные перевозки')),
                ('insurancePolicy', models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Страховой полис')),
                ('auto_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_type', to='Deal.TypeAuto', verbose_name='Тип авто')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='Фамилия')),
                ('tradingSet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TradingSet', to_field='name', verbose_name='Торговый сет')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['tradingSet'],
            },
        ),
    ]
