# Generated by Django 3.0.2 on 2020-03-18 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='dateOfBirth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, default='staticfiles/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Фото'),
        ),
    ]
