# Generated by Django 3.0.2 on 2020-03-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200318_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='autoOwnerPass',
            field=models.ImageField(default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Паспорт владельца'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='autoTechPassPhoto',
            field=models.ImageField(default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Технический паспорт авто'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driverLicense',
            field=models.ImageField(default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Водительская лицензия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driverPass',
            field=models.ImageField(default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Паспорт водителя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='insurancePolicy',
            field=models.ImageField(default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Страховой полис'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='internationalTransportationLicense',
            field=models.ImageField(default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Лицензия на международные перевозки'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='trailerTechPassPhoto',
            field=models.ImageField(default='static/blank-profile-picture-973460_6404.png', upload_to='static', verbose_name='Технический паспорт прицепа'),
        ),
    ]
