# Generated by Django 3.0.2 on 2020-02-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200219_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='username',
        ),
    ]
