# Generated by Django 3.0.2 on 2020-02-29 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['tradingSet'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='tradingset',
            options={'ordering': ['name'], 'verbose_name': 'Торговый сет', 'verbose_name_plural': 'Торговые сеты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name': 'Статус пользователя', 'verbose_name_plural': 'Статусы пользователя'},
        ),
        migrations.AddField(
            model_name='tradingset',
            name='IIN',
            field=models.CharField(blank=True, max_length=255, verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='tradingset',
            name='bankAccount',
            field=models.CharField(blank=True, max_length=255, verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='tradingset',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tradingset',
            name='legalAddress',
            field=models.CharField(blank=True, max_length=255, verbose_name='Юр. адрес'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='autoOwnerPass',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Паспорт владельца'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='autoTechPassPhoto',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Технический паспорт авто'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driverLicense',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Водительская лицензия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driverPass',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Паспорт водителя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='insurancePolicy',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Страховой полис'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='internationalTransportationLicense',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Лицензия на международные перевозки'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='trailerTechPassPhoto',
            field=models.ImageField(null=True, upload_to='static', verbose_name='Технический паспорт прицепа'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='tradingSet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TradingSet', to_field='name', verbose_name='Торговый сет'),
        ),
        migrations.AlterField(
            model_name='tradingset',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tradingset',
            name='ownerFullName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='tradingset',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default=1, max_length=6, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
    ]
