# Generated by Django 3.0.2 on 2020-03-26 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
