# Generated by Django 3.0.2 on 2020-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200326_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='dateOfBirth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
