# Generated by Django 3.0.2 on 2020-04-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200405_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Фамилия'),
        ),
    ]
