# Generated by Django 3.0.2 on 2020-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200405_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Менеджер'),
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
