# Generated by Django 3.0.2 on 2020-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200406_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Моб. телефон'),
        ),
    ]
