# Generated by Django 3.0.2 on 2020-04-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0022_auto_20200407_1447'),
        ('app', '0011_auto_20200407_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='auto_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_type', to='Deal.TypeAuto', verbose_name='Тип авто'),
        ),
    ]
